---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alertmanager-credentials
  namespace: prometheus
spec:
  interval: 24h
  path: k8s/prometheus/resources/alertmanager-external-secret/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: crd
      namespace: prometheus
    - name: crd
      namespace: external-secrets
