---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crd
  namespace: prometheus
spec:
  interval: 24h
  path: charts/kube-prometheus-stack/charts/crds/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator-crds
    namespace: prometheus
