---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repos-kustomization.yaml
  - crd-kustomization.yaml
  - prometheus-helm-release-kustomization.yaml
  - alertmanager-credentials-kustomization.yaml
