---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: x509-certificate-exporter
  namespace: x509-certificate-exporter
spec:
  interval: 24h
  url: https://charts.enix.io
