---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: node-problem-detector
      version: "2.3.6"
      sourceRef:
        kind: HelmRepository
        name: node-problem-detector
        namespace: node-problem-detector
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
