---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crd
  namespace: ansible-operator
spec:
  interval: 24h
  path: crds/
  prune: true
  sourceRef:
    kind: GitRepository
    name: ansible-operator
    namespace: ansible-operator
