---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opsgenie-api-key
  namespace: prometheus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: opsgenie-api-key
    template:
      type: Opaque
      data:
        opsgenie-api-key: "{{ .key }}"
  data:
    - secretKey: key
      remoteRef:
        key: opsgenie/opsgenie_api_key
