---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-problem-detector-helm-release
  namespace: node-problem-detector
spec:
  interval: 10m0s
  path: k8s/node-problem-detector/helm-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: prometheus-helm-release
      namespace: prometheus
