---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: node-problem-detector
spec:
  interval: 10m0s
  path: k8s/node-problem-detector/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
