---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: promtail
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: promtail
  values:
    serviceMonitor:
      enabled: true
      labels:
        heritage: Helm
        release: prometheus
    initContainer:
      - name: init
        image: docker.io/busybox:1.35
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - "sysctl -w fs.inotify.max_user_instances=1024 && sysctl -w fs.inotify.max_user_watches=1048576"
        securityContext:
          privileged: true
    extraArgs:
      - --client.external-labels=hostname=$(HOSTNAME),podname=$(PODNAME),src=lasagna
    extraEnv:
      - name: PODNAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
    config:
      clients:
        - url: https://l-p.casa-delle-coccinelle.link/api/prom/push
             ###### Systemd - Journald
      snippets:
        extraScrapeConfigs: |
          - job_name: journal
            journal:
              json: false
              path: /system-logs/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
              - source_labels: ['__journal__hostname']
                target_label: 'hostname'
             ###### Systemd - Journald
             ###### Audit
          - job_name: audit
            static_configs:
              - targets:
                 - localhost
                labels:
                  job: auditlog
                  __path__: /system-logs/audit/audit.log
             ###### Audit
             ###### Boot log
          - job_name: boot
            static_configs:
              - targets:
                 - localhost
                labels:
                  job: bootlog
                  __path__: /system-logs/boot.log
             ###### Boot log

    ###### System logs
    extraVolumes:
      - name: system-logs
        hostPath:
          path: /var/log

    extraVolumeMounts:
      - name: system-logs
        mountPath: /system-logs/
        readOnly: true
    ###### System logs

