---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  ref:
    tag: "v0.9.4"
  url: https://github.com/external-secrets/external-secrets
