---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/podmonitor.yaml
