---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: x509-certificate-exporter
  namespace: x509-certificate-exporter
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: x509-certificate-exporter
      version: "3.8.0"
      sourceRef:
        kind: HelmRepository
        name: x509-certificate-exporter
        namespace: x509-certificate-exporter
  values:
    sendgridcretsExporter:
      service:
        create: true
      prometheusServiceMonitor:
        create: true
      prometheusRules:
        create: true

    exposePerCertificateErrorMetrics: true
    exposeRelativeMetrics: true

    hostPathsExporter:
      daemonSets:
        nodes:
          watchDirectories:
            - /var/lib/rancher/k3s/server/tls/etcd/
            - /var/lib/rancher/k3s/server/tls/
            - /var/lib/rancher/k3s/server/tls/temporary-certs/
            - /var/lib/rancher/k3s/agent/
          watchKubeconfFiles:
            - /etc/rancher/k3s/k3s.yaml
