---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-resources
  namespace: external-secrets
spec:
  interval: 24h
  path: k8s/external-secrets/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: helm-release
      namespace: external-secrets
