---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  path: k8s/flux-system/kustomizations/flux-system-monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus
      namespace: flux-system
