---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-resources
  namespace: cert-manager
spec:
  interval: 24h
  path: k8s/cert-manager/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: helm-release
      namespace: cert-manager
    - name: crd
      namespace: external-secrets
    - name: helm-release
      namespace: external-secrets
