---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  interval: 24h
  url: https://charts.deliveryhero.io/
