collections:
  - name: kubernetes.core
    version: 2.2.2
  - name: ansible.posix
    version: 1.2.0
  - name: community.docker
    version: 3.4.6

roles:
  - name: k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  - name: pip
    src: geerlingguy.pip
  - name: docker
    src: geerlingguy.docker
  - name: fluxcd-bootstrap
    src: https://github.com/casa-delle-coccinelle/ansible-fluxcd-bootstrap.git
