apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    purpose: main-prometheus
spec:
  storageClassName: manual 
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/prometheus"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "48.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
  values:
    grafana:
      enabled: false
    coreDns:
      enabled: true
    prometheusOperator:
      enabled: true
      namespaces: {}
    prometheus:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: default-cluster-issuer
        hosts:
          - "prom-lasagna.casa-delle-coccinelle.link"
        path: /
        tls:
          - secretName: prom-general-tls
            hosts:
              - "prom-lasagna.casa-delle-coccinelle.link"
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: [ReadWriteOnce]
              resources:
                requests:
                  storage: 50Gi
              storageClassName: manual
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 90d
        replicas: 1
        shards: 1
        podMetadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-token: "true"
            vault.hashicorp.com/role: "prometheus"
            vault.hashicorp.com/agent-pre-populate: "false"
        thanos: {}
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: default-cluster-issuer
        hosts:
          - "a-prom-lasagna.casa-delle-coccinelle.link"
        path: /
        tls:
          - secretName: alerts-general-tls
            hosts:
              - "a-prom-lasagna.casa-delle-coccinelle.link"
      alertmanagerSpec:
        secrets:
          - opsgenie-api-key
      config:
        global:
          opsgenie_api_key_file: /etc/alertmanager/secrets/opsgenie-api-key/opsgenie-api-key
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: opsgenie
          routes:
            - match:
                alertname: Watchdog
              receiver: opsgenie
        receivers:
          - name: opsgenie
            opsgenie_configs:
              - responders:
                  - name: dimitko
                    type: 'team'
        templates:
          - '/etc/alertmanager/config/*.tmpl'
    kubeEtcd:
      enabled: true
      endpoints:
        - 172.16.0.13
      service:
        enabled: true
        port: 2381
        targetPort: 2381
