---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-operator-crds
  namespace: prometheus
spec:
  interval: 24h
  ref:
    tag: "kube-prometheus-stack-48.3.1"
  url: https://github.com/prometheus-community/helm-charts.git
