---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server-resources
  namespace: metrics-server
spec:
  interval: 24h
  path: k8s/metrics-server/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: helm-release
      namespace: metrics-server
