---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: metallb
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
  values:
    #loadBalancerClass: metallb
    rbac:
      create: true
    crds:
      enabled: false
    prometheus:
      scrapeAnnotations: true
      metricsPort: 7472
      serviceAccount: metallb
      namespace: metallb
      podMonitor:
        enabled: true
        jobLabel: "app.kubernetes.io/name"
        metricRelabelings: []
        relabelings: []
      prometheusRule:
        enabled: true
        staleConfig:
          enabled: true
          labels:
            severity: warning
        configNotLoaded:
          enabled: true
          labels:
            severity: warning
        addressPoolExhausted:
          enabled: true
          labels:
            severity: alert
        addressPoolUsage:
          enabled: true
          thresholds:
            - percent: 75
              labels:
                severity: warning
            - percent: 85
              labels:
                severity: warning
            - percent: 95
              labels:
                severity: alert
        bgpSessionDown:
          enabled: false
          labels:
            severity: alert
        extraAlerts: []
