---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: external-dns
      version: "1.13.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    podAnnotations: {}
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      interval: 1m
      scrapeTimeout: 10s

    interval: 1m
    triggerLoopOnEvent: false

    sources:
      - service
      - ingress

    policy: upsert-only

    registry: noop
    provider: pihole
    extraArgs:
      - --pihole-server=https://pihole-p.casa-delle-coccinelle.link
      - --pihole-password=admin
      - --pihole-tls-skip-verify
