---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: external-dns-credentials
    template:
      type: Opaque
      data:
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: terraform/modules/iam-user/certmanager-secret
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: terraform/modules/iam-user/certmanager-key
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: external-dns
      version: "1.13.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    podAnnotations: {}
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      interval: 1m
      scrapeTimeout: 10s

    interval: 1m
    triggerLoopOnEvent: false

    sources:
      - service
      - ingress

    policy: upsert-only

    registry: txt
    txtOwnerId: "lasagna"
    txtPrefix: "lasagna"
    provider: aws
    extraArgs: []
    env:
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-credentials
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: external-dns-credentials
            key: AWS_ACCESS_KEY_ID
