---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  dependsOn:
    - name: prometheus
      namespace: prometheus
  interval: 24h
  chart:
    spec:
      chart: metrics-server
      version: "3.11.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
  values:
    apiService:
      insecureSkipTLSVerify: true
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
