---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-release
  namespace: ingress-nginx
spec:
  interval: 24h
  path: k8s/ingress-nginx/helm-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: crd
      namespace: prometheus
