---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reppos
  namespace: ingress-nginx
spec:
  interval: 24h
  path: k8s/ingress-nginx/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
