---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      region: eu-central-1
      service: SecretsManager
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: aws-credentials
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: aws-credentials
