---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crd
  namespace: metallb
spec:
  interval: 24h
  path: ./config/crd/
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
    namespace: metallb
