---
- name: Update Fedora to 36 - prepare - force update packages
  shell: dnf --refresh upgrade -y

- name: Update Fedora to 36 - prepare - install dnf-update
  shell: dnf install dnf-plugin-system-upgrade --best -y

- name: Update Fedora to 36 - download
  shell: dnf system-upgrade download -y --refresh --releasever=35

- name: Update Fedora to 36 - upgrade
  shell: dnf system-upgrade reboot -y

